"""create_user_profiles_table

Revision ID: 6e4a6b14feee
Revises:
Create Date: 2025-06-04 20:48:41.317763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # Import SQLModel


# revision identifiers, used by Alembic.
revision: str = '6e4a6b14feee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('whatsapp_number', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('default_currency_code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False) # unique=False is typical for primary key indexes, but some prefer unique=True. Let's keep as instructed.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
