version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app/app  # Map local app directory to container for hot-reloading
    ports:
      - "8001:8000" # Map host port 8001 to container port 8000
    env_file:
      - .env.dev # Load environment variables from .env.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: juliao
      POSTGRES_PASSWORD: supersecretlocal
      POSTGRES_DB: juliaodb_dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optional: map host port 5432 to container port 5432 for direct db access

volumes:
  postgres_data_dev:
